# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jomason <jomason@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/07 10:30:52 by jomason           #+#    #+#              #
#    Updated: 2026/05/07 20:37:05 by jomason          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fdf
CC = cc
CFLAGS = -Wall -Wextra -Werror

SRC_DIR = src/
LIBFT_DIR = libft/
MLX42_DIR = mlx42/
MLX42_REPO = https://github.com/codam-coding-college/MLX42.git
INCLUDES = -I $(LIBFT_DIR) -I $(MLX42_DIR)/include/

SRC =	$(SRC_DIR)main.c \
		$(SRC_DIR)initialization.c \
		$(SRC_DIR)input_handler.c \
		$(SRC_DIR)map_allocation.c \
		$(SRC_DIR)map_parser.c \
		$(SRC_DIR)mem_management.c \
		$(SRC_DIR)projection.c \
		$(SRC_DIR)renderer.c \
		$(SRC_DIR)utils.c

OBJ = $(SRC:.c=.o)
LIBFT = $(LIBFT_DIR)libft.a
MLX42_LIB = $(MLX42_DIR)build/libmlx42.a

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
	LIBS = -lglfw -framework Cocoa -framework OpenGL -framework IOKit
endif
ifeq ($(UNAME_S),Linux)
	LIBS = -lglfw -lGL -ldl -lm -lpthread
endif

all: clone_mlx42 $(NAME)

$(NAME): $(OBJ) $(LIBFT) $(MLX42_LIB)
	$(CC) $(CFLAGS) $(OBJ) $(LIBFT) $(MLX42_LIB) -o $(NAME) $(LIBS)

$(LIBFT):
	make -C $(LIBFT_DIR)

$(MLX42_LIB):
	cmake -B $(MLX42_DIR)build -S $(MLX42_DIR)
	cmake --build $(MLX42_DIR)build

clone_mlx42:
	@if [ ! -d "$(MLX42_DIR).git" ]; then \
		echo "Cloning MLX42 library..."; \
		git clone $(MLX42_REPO) $(MLX42_DIR); \
	else \
		echo "MLX42 already cloned."; \
	fi

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	make -C $(LIBFT_DIR) clean
	rm -rf $(OBJ)

fclean: clean
	make -C $(LIBFT_DIR) fclean
	rm -rf $(NAME) $(MLX42_DIR)

re: fclean all

.PHONY: all bonus clean fclean re clone_mlx42